development:
  adapter: postgresql
  database: drop_that_bixi_dev
  host: localhost

test:
  adapter: postgresql
  database: drop_that_bixi_test
  host: localhost

production:
  adapter: postgresql
  database: drop_that_bixi
  host: localhost
